# -*- coding: utf-8 -*-
"""Dados_people.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vUP-GzaoJUjwlBvA1N_0xM-GYYofrutT
"""

# Lista de pessoas

users = [
    {"id": 1, "name": "João", "age": "25"},
    {"id": 2, "name": "Maria", "age": "32"},
    {"id": 3, "name": "Pedro", "age": "45"},
    {"id": 4, "name": "Ana", "age": "19"},
    {"id": 5, "name": "Luís", "age": "50"},
    {"id": 6, "name": "Sofia", "age": "28"},
    {"id": 7, "name": "Carlos", "age": "37"},
    {"id": 8, "name": "Marta", "age": "21"},
    {"id": 9, "name": "Ricardo", "age": "33"},
    {"id": 10, "name": "Beatriz", "age": "29"},
    {"id": 11, "name": "Antônio", "age": "55"},
    {"id": 12, "name": "Laura", "age": "26"},
    {"id": 13, "name": "André", "age": "42"},
    {"id": 14, "name": "Camila", "age": "31"},
    {"id": 15, "name": "Guilherme", "age": "39"},

]

print(users)